language: rust

rust:
  - stable

before_script: |
  cargo fmt --version
  cargo fmt -- --check
  cargo clippy --version
  cargo clippy
  cargo clean

deploy:
  provider: cargo
  token: $YOUR_API_TOKEN
  on:
    tags: true
notifications:
    email: false
