[package]
name = "datadog-statsd"
version = "0.1.0"
description = "A dogstatsd client for rust."
homepage = "https://github.com/minato128/rust-dogstatsd"
readme = "README.md"
license = "MIT"
authors = ["Mark Story <mark@mark-story.com>"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE.txt",
]
keywords = [ "datadog", "dogstatsd" ]

[dependencies]
rand = "^0.3"
